ControleDeContatos/Controllers/ContatoController.cs
using ControleDeContatos.Filters;
using ControleDeContatos.Helper;
using ControleDeContatos.Models;
using ControleDeContatos.Repositorio;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace ControleDeContatos.Controllers
{
    [PaginaParaUsuarioLogado]
    public class ContatoController : Controller
    {
        private readonly IContatoRepositorio _contatoRepositorio;
        private readonly ISessao _sessao;

        public ContatoController(IContatoRepositorio contatoRepositorio,
                                 ISessao sessao)
        {
            _contatoRepositorio = contatoRepositorio;
            _sessao = sessao;   
        }

        public IActionResult Index()
        {
            UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
            List<ContatoModel> contatos = _contatoRepositorio.BuscarTodos(usuarioLogado.Id);

            return View(contatos);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            ContatoModel contato = _contatoRepositorio.BuscarPorID(id);
            return View(contato);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            ContatoModel contato = _contatoRepositorio.BuscarPorID(id);
            return View(contato);
        }

        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _contatoRepositorio.Apagar(id);

                if(apagado) TempData["MensagemSucesso"] = "Registro apagado com sucesso!"; else TempData["MensagemErro"] = "Ops, não conseguimos cadastrar seu registro, tente novamante!";
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos apagar seu registro, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Criar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                    contato.UsuarioId = usuarioLogado.Id;

                    contato = _contatoRepositorio.Adicionar(contato);

                    TempData["MensagemSucesso"] = "Registro cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View(contato);
            }
            catch (Exception erro)
            { 
                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar seu registro, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Editar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    UsuarioModel usuarioLogado = _sessao.BuscarSessaoDoUsuario();
                    contato.UsuarioId = usuarioLogado.Id;

                    contato = _contatoRepositorio.Atualizar(contato);
                    TempData["MensagemSucesso"] = "Registro alterado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View(contato);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos atualizar seu registro, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

ControleDeContatos/Views/Contato/ApagarConfirmacao.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Confirmação apagar contato";
}

<div class="text-center">
    <h3>Realmente deseja apagar o contato (@Model.Nome)?</h3>
</div>

<a class="btn btn-primary btn-block" asp-action="Index" asp-controller="Contato" role="button">Cancelar exclusão</a>
<a class="btn btn-danger btn-block" asp-action="Apagar" asp-controller="Contato" asp-route-id="@Model.Id" role="button">Confirmar exclusão</a>

ControleDeContatos/Views/Contato/Criar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Criar de Registros";
}
<div class="text-center">

    <h1 class="display-4">Registrar Ponto</h1>

</div>

<form asp-controller="Contato" asp-action="Criar" method="post">
    <div class="mb-3">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder=" Digite aqui seu nome">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="mb-3">
        <label for="matricula">Matrícula</label>
        <input type="text" asp-for="Matricula" class="form-control" placeholder=" Digite aqui sua matrícula">
        @Html.ValidationMessageFor(x => x.Matricula)
    </div>

    <div class="mb-3">
        <label for="entrada">Entrada</label>
        <input type="DateTime-local" asp-for="Entrada" class="form-control" placeholder=" Registre sua entrada">

    </div>

    <div class="mb-3">
        <label for="saida">Saída</label>
        <input type="DateTime-local" asp-for="Saida" class="form-control" placeholder=" Registre sua saída">

    </div>

    <button type="submit" class="btn btn-primary btn-block">Registrar</button>
    <a class="btn btn-secondary btn-block" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
</form>

ControleDeContatos/Views/Contato/Editar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Editar Registros";
}
<div class="text-center">

    <h2 class="display-4">Editar Ponto</h2>

</div>

<form asp-controller="Contato" asp-action="Alterar" method="post">

    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder=" Digite aqui seu nome">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="matricula">Matrícula</label>
        <input type="text" asp-for="Matricula" class="form-control" placeholder=" Digite aqui sua matrícula">
        @Html.ValidationMessageFor(x => x.Matricula)
    </div>

    <div class="form-group">
        <label for="entrada">Entrada</label>
        <input type="DateTime-local" asp-for="Entrada" class="form-control" placeholder=" Registre sua entrada">
    </div>

    <div class="form-group">
        <label for="saida">Saída</label>
        <input type="DateTime-local" asp-for="Saida" class="form-control" placeholder=" Registre sua saída">
    </div>

    <button type="submit" class="btn btn-primary btn-block">Alterar</button>
    <a class="btn btn-secondary btn-block" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
</form>

ControleDeContatos/Views/Contato/Index.cshtml
@model List<ContatoModel>
@{
    ViewData["Title"] = "Listagem de Registros";
}

<div class="text-center">

   

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />

    <h2 class="display-4">Listagem de Registros</h2>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a class="btn btn-outline-primary"  asp-controller="Contato" asp-action="Criar" role="button">Adicionar novo registro</a>
    </div>

    <br />
    <table id="table-contatos" class="display" style="width:100%">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Matrícula</th>
                <th scope="col">Entrada</th>
                <th scope="col">Saída</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var contato in Model)
                {
                    <tr>
                        <th scope="row">@contato.Id</th>
                        <td>@contato.Nome</td>
                        <td>@contato.Matricula</td>
                        <td>@contato.Entrada</td>
                        <td>@contato.Saida</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" asp-action="Editar" asp-controller="Contato" asp-route-id="@contato.Id" class="btn btn-primary">Editar</a>
                                <a role="button" asp-action="ApagarConfirmacao" asp-controller="Contato" asp-route-id="@contato.Id" class="btn btn-danger">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="odd"><td valign="top" colspan="5">Nenhum registro encontrado</td></tr>
            }
        </tbody>
    </table>

</div>